### PR TITLE
Ensure slash-separated paths in the inspections reporter

### LINKED ISSUE #21: Wrong path format on Windows TeamCity instance
I'm getting no file details in my "**inspections** report" on my Windows TC instance.

image

The reason is that the file paths are emitted incorrectly. They need to be slashes also on Windows.

Note: The TSLint version of this reporter had already the same issue: https://github.com/ThaNarie/tslint-teamcity-reporter/pull/10

### PR DESCRIPTION
**Pull request by ulrichb**
Fixes #21.

See the issue description.

See also the corresponding PR in the TSLint formatter: https://github.com/ThaNarie/tslint-teamcity-reporter/pull/10

### CODE REVIEW

**Comment by andreogle** [comment]
Thanks a lot for this! I think it's worth adding this fix to the errors formatter as well

**Comment by ulrichb** [comment]
@andreogle That's funny, the TSLint maintainer had the same question.

Here my answer: https://github.com/ThaNarie/tslint-teamcity-reporter/pull/10#issuecomment-472572011 

No prob, I can change it too, but no guarantee if it is necessary (or may even break the test reporter).

BTW: IMO the test case reporter has no advantage other than it supports older TC versions, which have no custom inspections reporting. So I would suggest to make a new major version and (breaking) change the default to the inspections reporter.

**Comment by andreogle** [comment]
I think it should be fine to change the errors formatter too. I can't see how it might break things.

Yeah even though I've only used the test case reporter, I think I'm liking the inspections reporter more and more. The "Code Inspections" tab name also implies that it's for exactly this purpose. I'll change it and release a new major version once this fix is in.

**Comment by ulrichb** [comment]
I've changed it for the test case reporter too (although I saw that there it's just about presentation; the file path only seems to be part of the "test" name).

And thanks for considering changing the default.

**Comment by andreogle** [comment]
Thanks again for making this fix!

**Pull request merged**
